### ISSUE TITLE
Home Assistant integration?

### ISSUE THREAD

**Issue by BigFoot2020** [tadasdanielius/pyaltherma#1]
Hello!

Would You know if there is Home Assistant integration (custom component) done using this library?

Also here (in GitHub) version is 0.0.8, but in PyPI it shows version 0.0.11. What is difference between these?

**Comment by tadasdanielius** [comment]
Hi,

I have pushed new version to the repo. There are some bug fixes. So that should be both up to date.

Regarding Home Assistant, I am not aware if anyone else has created, but I have build my own component. Actually I build this library just for that. The component current status in early alpha and development phase. I am just testing it on my own and so far it is working for me. However, there are a lot to work on. At the moment I have not shared the code, but if you are interested I can put it on github.

**Comment by BigFoot2020** [comment]
Great! Would be very much interested in helping to test :-) and get local control.

**Comment by tadasdanielius** [comment]
You can find custom component [here](https://github.com/tadasdanielius/daikin_altherma). As I said, a lot of work is required to make it into a proper component. So, use it at your own risk. If you encounter any issues I might be able to help but can't promise that :).

**Comment by BigFoot2020** [comment]
Many thanks for sharing! First test done and everything seems to be working as expected. There was a warning in the log to create issue for author, so I will do that under correct repository (should be minor change).

FYI: I am currently using [this](https://github.com/BigFoot2020/daikin_residential_brp069a62), which would break if my Internet connection is down (luckily not that often) or when there is problem with cloud (recent AWS issue had an affect).

**Comment by BigFoot2020** [comment]
Library version in GitHub is still 0.0.8...

**Comment by tadasdanielius** [comment]
I am sure this commit 0635bc7bc38a8f5b6fa4f03acf3f7c2383c1c6c9 bumps to 0.0.11

**Comment by BigFoot2020** [comment]
Sorry, that was my mistake, looked ino wrong place. I have correct version now.
Another question, would you be willing to share your work here: https://community.home-assistant.io/t/daikin-heat-pump-altherma-integration/202760/70?
