### ISSUE TITLE
Integrate with altherma 3 bigfoot

### ISSUE THREAD

**Issue by mangio85** [tadasdanielius/pyaltherma#4]
Hi Tadas, thanks for your contribution, I hope it will be of help to others as well.
In a discussion I saw your project and analyzed it, 
but unfortunately I don't understand how to insert it.
I currently have access in ha to my LAN ADAPTER brp069a61 through the bigfoot hacs. 
I have some parameters, but unfortunately nothing to do with those that I was able to admire with espaltherma.
Could you tell me how to integrate your code and if there are margins of approach to an important quantity of values ​​coming from the sensors?
I would also like to help you if it is possible.  Doing tests.  Unfortunately, however, I'm just starting out with Ha.
A warm greeting.  And thanks.

**Comment by tadasdanielius** [comment]
Hi,

If you want to integrate with HA you should check [daikin altherma](https://github.com/tadasdanielius/daikin_altherma) repo. There you will find the HA integration which is using this library, or you can just simply search in HACS for daikin altherma.
Regarding the data, I don't think you will get much more compared to the bigfoot's integration. The difference is that bigfoot integration works over cloud, that is fetching info from the cloud, while this one works locally so you do not depend on the internet connection..
With espaltherma you can get much more info because you need to connect to the board directly.
